Description: 
  Template to provision an EC2 Instance with httpd installed.

Parameters:  
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

#  InstanceImageId:
#    Description: EC2 Image Id from this region
#    Type: AWS::EC2::Image::Id
#    Default: ami-076e39b6b14e3bb20
    
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-04bf6dcdc9ab498ca
    us-west-1:
      AMI: ami-000279759c4819ddf
    eu-west-1:
      AMI: ami-014ce76919b528bff
    ap-southeast-2:
      AMI: ami-06ce513624b435a22
    ap-northeast-1:
      AMI: ami-034968955444c1fd9

Resources:

  Ec2AdminIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  Ec2AdminInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: [!Ref Ec2AdminIamRole]        
        

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http and ssh to client host 
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  
          
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      IamInstanceProfile: !Ref Ec2AdminInstanceProfile  
      KeyName: !Ref KeyPairName
      UserData:
        Fn::Base64: |
            #!/bin/bash -xe
            iptables -A OUTPUT -m owner ! --uid-owner root -d 169.254.169.254 -j DROP
            yum update -y
            yum install -y httpd
            yum install -y git
            service httpd start
            chkconfig httpd on
            yum install -y awslogs
            sed -i 's/us-east-1/ap-southeast-2/g' /etc/awslogs/awscli.conf
            sed -i '/^log_group_name/d' /etc/awslogs/awslogs.conf
            sed -i '$s/$/\nlog_group_name = httpd/' /etc/awslogs/awslogs.conf
            sleep 5
            git clone https://github.com/cloudacademy/static-website-example.git
            cp -r static-website-example/* /var/www/html/
            sleep 5
            service awslogsd start
            systemctl enable awslogsd         
 
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: Web Server
        - Key: Type
          Value: Web Server Instance
          
  IPAddress:
    Type: AWS::EC2::EIP
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'Ec2Instance'
      EIP: !Ref 'IPAddress'
      
Outputs:
  InstanceId:
    Description: InstanceId of the EC2 instance
    Value: !Ref Ec2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt 
      - Ec2Instance
      - PublicIp
